Web/10 system allows a visitor to register a publisher account
GOOFR-Group/gaming-store pull request #65
Opened 2024-11-30 22:48 UTC by rllko

Refs: #10 

## Summary

Added functionality to the register page + necessary functions

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> + * @param newPublisher User to be created.
```suggestion
 * @param newPublisher Publisher to be created.
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/routes/distribute/register.tsx
> +    picture: z
Picture can be remove since it's not used in the form.

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> + * @returns a NewPublisher instance.
```suggestion
 * @returns Publisher created.
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> +export async function getPublisher(id: string) {
This function is not used anywhere, so it can be removed.

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> +  return user;
```suggestion
  const publisher = (await response.json()) as Publisher;

  return publisher;
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/domain/publisher.ts
> +  email?: string;
Email is a required credential.

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/domain/publisher.ts
> +export interface EditablePublisher {
This is not used in this PR so it can be removed.

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/domain/publisher.ts
> + * Represents a new NewPublisher/PublisherPost.
```suggestion
 * Represents a new publisher.
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/domain/publisher.ts
> + * Represents a Publisher.
```suggestion
 * Represents a publisher.
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> + * @throws {Conflict} Username, email or vatin already exist.
```suggestion
 * @throws {Conflict} Email or vatin already exist.
```

2024-12-14 18:17 UTC, joaotomaspinheiro commented on web/src/routes/distribute/register.tsx
> +          case "publisher_name_already_exists":
This case shouldn't exist.

2024-12-15 23:55 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> + * Signs in a user with their credentials.
```suggestion
 * Signs in a publisher with their credentials.
```

2024-12-15 23:55 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> + * @param credentials User credentials.
```suggestion
 * @param credentials Publisher credentials.
```

2024-12-15 23:55 UTC, joaotomaspinheiro commented on web/src/lib/api.ts
> +    credentials: "include",
This is not needed.

2024-12-16 00:05 UTC, joaotomaspinheiro commented on web/src/routes/distribute/register.tsx
> +  function onSubmit(data: RegisterSchemaType) {
```suggestion
  /**
   * Handles form submission.
   * @param data Form data.
   */
  function onSubmit(data: RegisterSchemaType) {
```

2024-12-16 10:22 UTC, Goncalo-Marques commented on web/src/routes/distribute/register.tsx
> +          case "user_email_already_exists":
```suggestion
          case "publisher_email_already_exists":
```

2024-12-16 10:25 UTC, Goncalo-Marques commented on web/src/routes/distribute/register.tsx
> +        description: "Please try again later or contact the support team.",
There is a const with this toast to avoid duplicated code

2024-12-22 00:59 UTC, Goncalo-Marques approved these changes

2024-12-22 01:01 UTC, Goncalo-Marques requested changes
I think that @joaotomaspinheiro still needs to perform some changes regarding the page redirects when a publisher is not signed in

2024-12-22 19:48 UTC, Goncalo-Marques approved these changes

2024-12-22 19:49 UTC, joaotomaspinheiro approved these changes

2024-12-22 19:49 UTC, merged